# SPDX-FileCopyrightText: 2026 Toyota Connected North America
# SPDX-License-Identifier: Apache-2.0

include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - lib/src/bindings.g.dart
    - build/**
