// SPDX-FileCopyrightText: 2026 Toyota Connected North America
// SPDX-License-Identifier: Apache-2.0

//! ihs_wl_server: an embedded Wayland server (smithay) that hands each client
//! toplevel's surfaces to ivi-homescreen as zero-copy platform-view layers.
//! The shell is the only compositor; this module never renders.
//!
//! This file is the C ABI (`include/ihs_wl.h`, generated by cbindgen). Same
//! boundary rules as ihs_shared: C types only, `struct_size` first, integer
//! result codes, and a thread-local `ihs_wl_last_error()`. Every entry point
//! catches panics -- one must never unwind into the shell.

use std::any::Any;
use std::cell::RefCell;
use std::ffi::{c_char, c_int, CStr, CString};
use std::panic::{self, AssertUnwindSafe};

mod buffers;
mod caps;
mod config;
mod error;
#[doc(hidden)]
pub mod ffi;
mod handlers;
mod input;
mod log;
mod nodes;
#[doc(hidden)]
pub mod observe;
mod pacing;
mod params;
mod staging;
mod state;
mod submit;
mod syncobj;
mod thread;
mod timing;
mod tree;
mod view;

pub use config::Config;
pub use error::{Error, Result};

/// Result codes. Entry points return these as `int`.
#[repr(i32)]
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum IhsWlResult {
    Ok = 0,
    /// Null or malformed arguments, or a bad `struct_size`.
    ErrInvalid = -1,
    /// `ihs_wl_start` while running (e.g. after a hot restart). The server
    /// and its clients carry on; re-created views rebind to their toplevels.
    ErrAlreadyRunning = -2,
    ErrNotRunning = -3,
    /// Socket bind or other OS failure.
    ErrIo = -4,
    /// Internal failure, including a caught panic.
    ErrInternal = -5,
    /// Not implemented in this build.
    ErrUnsupported = -6,
    /// The output buffer is too small.
    ErrTooSmall = -7,
}

/// Start-up configuration.
#[repr(C)]
pub struct IhsWlConfig {
    /// `sizeof(IhsWlConfig)`.
    pub struct_size: usize,
    /// Socket name under `$XDG_RUNTIME_DIR`. NULL = auto: `wayland-ihs-N` when
    /// this process is itself a Wayland client, else `wayland-N`.
    pub socket_name: *const c_char,
}

/// `IhsWlPointerEvent::kind`.
#[repr(u32)]
pub enum IhsWlPointerKind {
    Enter = 0,
    Leave = 1,
    Motion = 2,
    Button = 3,
    Axis = 4,
}

/// Pointer input, in view-local logical pixels.
#[repr(C)]
#[derive(Clone, Copy, Debug)]
pub struct IhsWlPointerEvent {
    pub struct_size: usize,
    /// `IhsWlPointerKind`.
    pub kind: u32,
    /// Linux `BTN_*` code, for `Button`.
    pub button: u32,
    pub x: f64,
    pub y: f64,
    /// 1 = pressed, for `Button`.
    pub pressed: u32,
    /// `wl_pointer.axis_source`, for `Axis`.
    pub axis_source: u32,
    /// Scroll distance in logical px, for `Axis`.
    pub axis_x: f64,
    pub axis_y: f64,
    /// High-resolution wheel steps (120 = one detent); 0 when not a wheel.
    pub value120_x: i32,
    pub value120_y: i32,
    pub time_us: u64,
}

/// `IhsWlTouchEvent::kind`.
#[repr(u32)]
pub enum IhsWlTouchKind {
    Down = 0,
    Up = 1,
    Motion = 2,
    Cancel = 3,
    /// End of a batch of touch events.
    Frame = 4,
}

/// Touch input, in view-local logical pixels.
#[repr(C)]
#[derive(Clone, Copy, Debug)]
pub struct IhsWlTouchEvent {
    pub struct_size: usize,
    /// `IhsWlTouchKind`.
    pub kind: u32,
    /// Contact id (Flutter's `PointerEvent.pointer`).
    pub slot: i32,
    pub x: f64,
    pub y: f64,
    pub time_us: u64,
}

thread_local! {
    static LAST_ERROR: RefCell<CString> = RefCell::new(CString::default());
}

fn set_last_error(message: &str) {
    let message = CString::new(message.replace('\0', "")).unwrap();
    LAST_ERROR.with(|e| *e.borrow_mut() = message);
}

pub(crate) fn panic_message(payload: &(dyn Any + Send)) -> String {
    payload
        .downcast_ref::<&str>()
        .map(|s| s.to_string())
        .or_else(|| payload.downcast_ref::<String>().cloned())
        .unwrap_or_else(|| "unknown panic".into())
}

/// Run `f` as an FFI entry point: map errors to codes, record the message,
/// and turn a panic into `IhsWlResult::ErrInternal as c_int`.
fn guard(name: &str, f: impl FnOnce() -> Result<c_int>) -> c_int {
    match panic::catch_unwind(AssertUnwindSafe(f)) {
        Ok(Ok(rc)) => rc,
        Ok(Err(e)) => {
            // Neither is worth a line per call: a hot restart starts again,
            // and a view may send input after a stop.
            if e.code != IhsWlResult::ErrAlreadyRunning as c_int
                && e.code != IhsWlResult::ErrNotRunning as c_int
            {
                tracing::warn!("{name}: {}", e.message);
            }
            set_last_error(&e.message);
            e.code
        }
        Err(payload) => {
            let message = format!("{name}: panic: {}", panic_message(&*payload));
            tracing::error!("{message}");
            set_last_error(&message);
            IhsWlResult::ErrInternal as c_int
        }
    }
}

/// Read a `struct_size`-first argument, rejecting NULL or a short struct.
unsafe fn sized<'a, T>(name: &str, p: *const T) -> Result<&'a T> {
    if p.is_null() {
        return Err(Error::invalid(format!("{name} is NULL")));
    }
    let size = *(p as *const usize);
    if size < std::mem::size_of::<T>() {
        return Err(Error::invalid(format!(
            "{name}: struct_size {size} < {}",
            std::mem::size_of::<T>()
        )));
    }
    Ok(&*p)
}

unsafe fn parse_config(cfg: *const IhsWlConfig) -> Result<Config> {
    let cfg = sized("config", cfg)?;
    let socket_name = if cfg.socket_name.is_null() {
        None
    } else {
        let name = CStr::from_ptr(cfg.socket_name)
            .to_str()
            .map_err(|_| Error::invalid("socket_name is not UTF-8"))?;
        if name.is_empty() || name.contains('/') {
            return Err(Error::invalid(format!("bad socket_name {name:?}")));
        }
        Some(name.to_owned())
    };
    Ok(Config { socket_name })
}

/// Start the server: spawn the compositor thread, bind the socket and
/// register the `ihs_wl/toplevel` platform-view factory. Returns once the
/// socket is listening, or with the error that stopped it.
///
/// # Safety
/// `cfg` must point to a readable `IhsWlConfig` whose strings are
/// NUL-terminated for the duration of the call.
#[no_mangle]
pub unsafe extern "C" fn ihs_wl_start(cfg: *const IhsWlConfig) -> c_int {
    guard("ihs_wl_start", || {
        thread::start(parse_config(cfg)?)?;
        Ok(IhsWlResult::Ok as c_int)
    })
}

/// Stop the server: unregister the factory, disconnect every client, remove
/// the socket and join the compositor thread. A no-op when not running.
#[no_mangle]
pub extern "C" fn ihs_wl_stop() {
    guard("ihs_wl_stop", || match thread::stop() {
        Err(e) if e.code == IhsWlResult::ErrNotRunning as c_int => Ok(IhsWlResult::Ok as c_int),
        r => r.map(|()| IhsWlResult::Ok as c_int),
    });
}

/// The bound socket name (e.g. `wayland-ihs-0`), or NULL when not running.
/// Valid until `ihs_wl_stop`.
#[no_mangle]
pub extern "C" fn ihs_wl_socket_name() -> *const c_char {
    panic::catch_unwind(thread::socket_name_ptr).unwrap_or(std::ptr::null())
}

/// Issue an xdg-activation token for a client about to be launched:
/// the launcher exports it as `XDG_ACTIVATION_TOKEN` and passes the same
/// token in the view's creationParams. Writes a NUL-terminated token of at
/// most `cap` bytes to `out`; returns its length.
///
/// # Safety
/// `out` must be writable for `cap` bytes.
#[no_mangle]
pub unsafe extern "C" fn ihs_wl_activation_token(out: *mut c_char, cap: usize) -> c_int {
    let _ = (out, cap);
    unsupported("ihs_wl_activation_token")
}

/// Pointer input for the view `view_id`. Any thread; only enqueues. Returns
/// the client's cursor shape (`wp_cursor_shape_device_v1.shape`), 0 while
/// none is known, or a negative error.
///
/// # Safety
/// `ev` must point to a readable `IhsWlPointerEvent`.
#[no_mangle]
pub unsafe extern "C" fn ihs_wl_pointer(view_id: i32, ev: *const IhsWlPointerEvent) -> c_int {
    guard("ihs_wl_pointer", || {
        let event = *sized("event", ev)?;
        if event.kind > IhsWlPointerKind::Axis as u32 {
            return Err(Error::invalid(format!("bad pointer kind {}", event.kind)));
        }
        if ![event.x, event.y, event.axis_x, event.axis_y]
            .iter()
            .all(|v| v.is_finite())
        {
            return Err(Error::invalid("pointer event is not finite"));
        }
        thread::send(thread::Cmd::Pointer { view_id, event })?;
        Ok(0)
    })
}

/// Touch input for the view `view_id`. Any thread; only enqueues.
///
/// # Safety
/// `ev` must point to a readable `IhsWlTouchEvent`.
#[no_mangle]
pub unsafe extern "C" fn ihs_wl_touch(view_id: i32, ev: *const IhsWlTouchEvent) -> c_int {
    guard("ihs_wl_touch", || {
        let event = *sized("event", ev)?;
        if event.kind > IhsWlTouchKind::Frame as u32 {
            return Err(Error::invalid(format!("bad touch kind {}", event.kind)));
        }
        if event.slot < 0 || !event.x.is_finite() || !event.y.is_finite() {
            return Err(Error::invalid("bad touch slot or position"));
        }
        thread::send(thread::Cmd::Touch { view_id, event })?;
        Ok(IhsWlResult::Ok as c_int)
    })
}

/// A key press (`pressed` = 1) or release for the view `view_id`, as an evdev
/// code. Any thread; only enqueues. Goes to the client only while the view
/// has keyboard focus.
#[no_mangle]
pub extern "C" fn ihs_wl_key(view_id: i32, evdev: u32, pressed: u32, time_us: u64) -> c_int {
    guard("ihs_wl_key", || {
        if evdev > input::KEY_MAX {
            return Err(Error::invalid(format!("bad evdev code {evdev}")));
        }
        thread::send(thread::Cmd::Key {
            view_id,
            evdev,
            pressed: pressed != 0,
            time_us,
        })?;
        Ok(IhsWlResult::Ok as c_int)
    })
}

/// Give (`focused` = 1) or take keyboard focus for the view `view_id`. Any
/// thread; only enqueues. Taking it from a view that does not have it is a
/// no-op.
#[no_mangle]
pub extern "C" fn ihs_wl_focus(view_id: i32, focused: u32) -> c_int {
    guard("ihs_wl_focus", || {
        thread::send(thread::Cmd::Focus {
            view_id,
            focused: focused != 0,
        })?;
        Ok(IhsWlResult::Ok as c_int)
    })
}

/// The message for the last failed call on this thread; never NULL, empty
/// when there has been none. Valid until the next call on this thread.
#[no_mangle]
pub extern "C" fn ihs_wl_last_error() -> *const c_char {
    LAST_ERROR.with(|e| e.borrow().as_ptr())
}

fn unsupported(name: &str) -> c_int {
    guard(name, || {
        Err(Error::new(
            IhsWlResult::ErrUnsupported as c_int,
            format!("{name}: not implemented yet"),
        ))
    })
}

/// Rust entry points, for tests and Rust embedders.
pub fn start(config: Config) -> Result<()> {
    thread::start(config)
}

pub fn stop() -> Result<()> {
    thread::stop()
}

pub fn socket_name() -> Option<String> {
    thread::socket_name()
}
